apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log
    output.elasticsearch:
      hosts: ['elasticsearch-service.monitoring.svc.cluster.local:9200']

