# apiVersion: v1
# kind: Service
# metadata:
#   name: web-service
# spec:
#   selector:
#     app: web
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: app
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort    #Using minikube on my local MAC and currently doesn't own any cloud account, that's why using Nodeport instead of LoadBalancer.
