version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - docker/web/.env
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: docker/mongo/Dockerfile
    ports:
      - "27017:27017"

